### ISSUE TITLE
SHT31 crashes when readSensorData.read data is 0 length

### ISSUE THREAD

**Issue by matteliot** [alwint3r/sht31-node#3]
it might be a decent idea to check for that and exit early or similar.

Also- doesn't this code, as-is work for you or are there some mods that aren't checked in? I'm really dying to get this sensor giving me data.

Thanks

**Comment by alwint3r** [comment]
Can you give me the details of the crash such as the stack trace, perhaps? That would really help me to fix the problem.

**Comment by matteliot** [comment]
```javascript
readSensorData() {
    return this.writeCommand(commands.SHT31_MEAS_HIGHREP)
      .then(() =>{utils.delay(500);})
      .then(() => {this.wire.readAsync(6);} )
      .then((read) => {

        let rawTemperature;
        let rawHumidity;

        rawTemperature = **read[0]**;  <<----- crash here since read is undefined

```


```
Error: TypeError: Cannot read property '0' of undefined  
Unhandled rejection Error: Cannot read from device  
  at i2c.read (/projects/sht31-node/node_modules/i2c/lib/i2c.coffee:71:10)  
  at i2c.tryCatcher (/projects/sht31- 
node/node_modules/bluebird/js/release/util.js:16:23)  
  at i2c.ret [as readAsync] (<anonymous>:13:39)  
  at writeCommand.then.then (/projects/sht31-node/src/index.js:40:59)  
  at tryCatcher (/projects/sht31-node/node_modules/bluebird/js/release/util.js:16:23)  
  at Promise._settlePromiseFromHandler (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:512:31)  
  at Promise._settlePromise (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:569:18)  
  at Promise._settlePromise0 (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:614:10)  
  at Promise._settlePromises (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:693:18)  
  at Promise._fulfill (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:638:18)  
  at Promise._resolveCallback (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:432:57)  
  at Promise._settlePromiseFromHandler (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:524:17)  
  at Promise._settlePromise (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:569:18)  
  at Promise._settlePromise0 (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:614:10)  
  at Promise._settlePromises (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:693:18)  
  at Promise._fulfill (/projects/sht31-node/node_modules/bluebird/js/release/promise.js:638:18)  
  at /projects/sht31-node/node_modules/bluebird/js/release/nodeback.js:42:21  
  at Immediate.<anonymous> (/projects/sht31-node/node_modules/i2c/lib/i2c.coffee:54:9)  
  at runCallback (timers.js:672:20)  
  at tryOnImmediate (timers.js:645:5)  
  at processImmediate [as _immediateCallback] (timers.js:617:5)    
```

**Comment by alwint3r** [comment]
`Unhandled rejection Error: Cannot read from device` means that either you have no permission to read from I2C devices, or the I2C device is not detected. Please see [this link](https://learn.sparkfun.com/tutorials/raspberry-pi-spi-and-i2c-tutorial) for I2C usage on raspberry pi. Also, [here](https://github.com/alwint3r/sht31-node/issues/1#issuecomment-310556404) regarding the usage of this module / library.

**Comment by matteliot** [comment]
yes, I'm familiar with the pi i2c setup.

I2c is definitely enabled and working as expected with python-based and C-based sht31 libs I've tried.

**Comment by alwint3r** [comment]
Ok then. I'll update the code to handle the case where the `read` variable is falsy.
